#!/usr/bin/env node
/**
 * Fetch posts from Notion → write `content/blog/<slug>/en.md`.
 *
 * Designed to run in GitHub Actions BEFORE `translate-posts.mjs`. The
 * translator picks up any new/changed en.md and produces es.md (the
 * existing translator already handles the `coverAlt` frontmatter field
 * — it gets translated to ES along with title/d/r).
 *
 * Filter: `Status = "Ready to publish"`. The author marks posts as such
 * when finished writing. After this script + commit + push succeed, the
 * follow-up `notion-mark-published.mjs` flips the same pages to
 * `Status = "Published"` so they're not re-processed on the next cron.
 *
 * To re-publish (update an already-live post): change Status back to
 * `Ready to publish` in Notion. Same flow runs.
 *
 * Auto-derived fields (NOT manual properties in Notion):
 *   - `r` (read time): computed from word count at ~200 wpm
 *   - `coverAlt`: generated by gpt-4o-mini vision from the cover image
 *     + post title/category context. Translated to ES by translate-posts.
 *
 * Cover image flow:
 *   - User drags/drops an image into the `Cover` FILES property
 *   - This script downloads the file from Notion's signed URL
 *   - Resizes to ≤1600px wide via sharp (preserves aspect, JPEG q85)
 *   - Saves to public/blog-covers/<slug>.<ext>
 *   - Emits `cover: /blog-covers/<slug>.<ext>` in the frontmatter
 *   - The site picks it up via the existing post.cover handling
 *
 * Output to $GITHUB_OUTPUT: `processed=<json>` consumed by the workflow
 * for the follow-up status flip step.
 *
 * Required env:
 *   NOTION_TOKEN          — internal integration token
 *   NOTION_POSTS_DB       — database id (32-char hex from URL)
 *   AI_GATEWAY_API_KEY    — used for the alt-text vision call
 */
import { Client } from "@notionhq/client";
import { NotionToMarkdown } from "notion-to-md";
import sharp from "sharp";
import {
  appendFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const VALID_CATEGORIES = new Set(["gitops", "migrations", "finops", "platform"]);
const VALID_TRANSLATORS = new Set([
  "deepseek-v4-pro",
  "deepseek-v4-flash",
  "claude-sonnet-4-6",
]);
const SLUG_REGEX = /^[a-z0-9][a-z0-9-]*[a-z0-9]$/;
const COVERS_DIR = path.join("public", "blog-covers");
const READ_WPM = 200; // standard reading speed for technical content
const COVER_MAX_WIDTH = 1600;
const COVER_QUALITY = 85;
const ALT_MODEL = "openai/gpt-4o-mini";
const AI_GATEWAY_URL = "https://ai-gateway.vercel.sh/v1/chat/completions";

function requireEnv(name) {
  const v = process.env[name];
  if (!v) {
    console.error(`[notion] missing env var: ${name}`);
    process.exit(1);
  }
  return v;
}

function plainText(rich) {
  if (!rich) return "";
  return rich.map((t) => t.plain_text).join("");
}

function escYaml(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Word-count → "N min" string. Floors at 1, otherwise rounds. */
function computeReadTime(body) {
  const words = body.trim().split(/\s+/).filter(Boolean).length;
  const min = Math.max(1, Math.round(words / READ_WPM));
  return `${min} min`;
}

/**
 * Download cover from Notion (signed URL), resize, save under
 * public/blog-covers/<slug>.<ext>. Returns the relative path for
 * use in frontmatter, or null if the post has no cover.
 */
async function downloadAndSaveCover(slug, fileProp) {
  if (!fileProp || !fileProp.files || fileProp.files.length === 0) {
    return null;
  }
  const file = fileProp.files[0];
  const url = file.type === "external" ? file.external.url : file.file?.url;
  if (!url) return null;

  console.log(`[notion] downloading cover for ${slug}`);
  const res = await fetch(url);
  if (!res.ok) {
    console.warn(`[notion] cover download failed for ${slug}: ${res.status}`);
    return null;
  }
  const inputBuf = Buffer.from(await res.arrayBuffer());

  // Always normalize to JPEG so the on-disk file extension is stable
  // regardless of what the user uploaded (PNG, HEIC, WEBP, etc.).
  const outBuf = await sharp(inputBuf)
    .rotate() // honor EXIF orientation (iPhone uploads)
    .resize({ width: COVER_MAX_WIDTH, withoutEnlargement: true })
    .jpeg({ quality: COVER_QUALITY, mozjpeg: true })
    .toBuffer();

  mkdirSync(COVERS_DIR, { recursive: true });
  const outPath = path.join(COVERS_DIR, `${slug}.jpg`);
  writeFileSync(outPath, outBuf);
  const sizeKB = Math.round(outBuf.length / 1024);
  console.log(`[notion] saved ${outPath} (${sizeKB}KB)`);
  return `/blog-covers/${slug}.jpg`;
}

/**
 * Generate concise EN alt text for the cover image via Vercel AI Gateway
 * (gpt-4o-mini vision). The translator pipeline will translate this to
 * ES later as part of its normal frontmatter handling.
 */
async function generateAltText({ slug, title, category, coverPath }) {
  if (!coverPath) return null;
  const apiKey = process.env.AI_GATEWAY_API_KEY;
  if (!apiKey) {
    console.warn(
      `[notion] no AI_GATEWAY_API_KEY — skipping alt text generation for ${slug}`
    );
    return null;
  }

  // Re-read the on-disk file (we just saved it) and base64-encode for
  // the vision API. Avoids re-hitting the Notion signed URL which may
  // already have been used.
  const buf = (await import("node:fs/promises")).then((fs) =>
    fs.readFile(path.join(COVERS_DIR, `${slug}.jpg`))
  );
  const imageBuf = await buf;
  const dataUrl = `data:image/jpeg;base64,${imageBuf.toString("base64")}`;

  const body = {
    model: ALT_MODEL,
    messages: [
      {
        role: "system",
        content:
          "You write concise, accurate alt text for blog post cover images. One sentence. Describe what the image actually shows so screen-reader users understand its content. Do not start with 'image of', 'photo of', or 'screenshot of'. 120 characters max.",
      },
      {
        role: "user",
        content: [
          {
            type: "text",
            text: `Cover image for a blog post titled "${title}" (category: ${category}). Write the alt text.`,
          },
          {
            type: "image_url",
            image_url: { url: dataUrl, detail: "low" },
          },
        ],
      },
    ],
    max_tokens: 80,
    temperature: 0.3,
  };

  const res = await fetch(AI_GATEWAY_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const errText = await res.text();
    console.warn(
      `[notion] alt text generation failed for ${slug}: ${res.status} ${errText.slice(0, 200)}`
    );
    return null;
  }
  const json = await res.json();
  const alt = json.choices?.[0]?.message?.content?.trim();
  if (!alt) return null;
  // Strip wrapping quotes and any trailing period for cleaner YAML.
  const cleaned = alt.replace(/^["']|["']$/g, "").replace(/\.$/, "");
  console.log(`[notion]   alt: "${cleaned}"`);
  return cleaned;
}

async function main() {
  const notion = new Client({ auth: requireEnv("NOTION_TOKEN") });
  const databaseId = requireEnv("NOTION_POSTS_DB");
  const n2m = new NotionToMarkdown({ notionClient: notion });

  console.log(
    `[notion] querying database ${databaseId} for Status="Ready to publish"`
  );
  // @notionhq/client v5 split databases into containers + data sources.
  // databases.query was removed; resolve the data source first and call
  // dataSources.query with the same filter.
  const db = await notion.databases.retrieve({ database_id: databaseId });
  const dataSourceId = db.data_sources?.[0]?.id;
  if (!dataSourceId) {
    console.error(
      `[notion] fatal: database ${databaseId} has no data sources`
    );
    process.exit(1);
  }
  const { results } = await notion.dataSources.query({
    data_source_id: dataSourceId,
    filter: { property: "Status", select: { equals: "Ready to publish" } },
  });
  console.log(`[notion] found ${results.length} page(s) to publish`);

  const processed = [];
  for (const page of results) {
    const props = page.properties;

    const slug = plainText(props.Slug?.rich_text).trim();
    if (!SLUG_REGEX.test(slug)) {
      console.warn(`[notion] skip ${page.id}: invalid slug "${slug}"`);
      continue;
    }

    const title = plainText(props.Title?.title).trim();
    if (!title) {
      console.warn(`[notion] skip ${slug}: missing Title`);
      continue;
    }

    const date = props.Date?.date?.start;
    if (!date) {
      console.warn(`[notion] skip ${slug}: missing Date`);
      continue;
    }

    const d = plainText(props["Display Date"]?.rich_text).trim();
    const category = props.Category?.select?.name?.trim();

    if (!d) {
      console.warn(`[notion] skip ${slug}: missing Display Date`);
      continue;
    }
    if (!category || !VALID_CATEGORIES.has(category)) {
      console.warn(
        `[notion] skip ${slug}: invalid category "${category}". Allowed: ${[...VALID_CATEGORIES].join(", ")}`
      );
      continue;
    }

    const translatorRaw = props["Translator override"]?.select?.name;
    const translator =
      translatorRaw && translatorRaw !== "(default)" && VALID_TRANSLATORS.has(translatorRaw)
        ? translatorRaw
        : null;

    // 1. Convert page body to markdown FIRST — needed for read time
    //    calculation and for the final write.
    const blocks = await n2m.pageToMarkdown(page.id);
    const body = (n2m.toMarkdownString(blocks).parent ?? "").trim();
    const readTime = computeReadTime(body);

    // 2. Cover image: download → resize → save under public/.
    let coverPath = null;
    let coverAlt = null;
    try {
      coverPath = await downloadAndSaveCover(slug, props.Cover);
      if (coverPath) {
        coverAlt = await generateAltText({
          slug,
          title,
          category,
          coverPath,
        });
      }
    } catch (err) {
      console.warn(
        `[notion] cover handling failed for ${slug}: ${err.message}. Continuing without cover.`
      );
    }

    // 3. Build frontmatter + body and write.
    const fmLines = [
      "---",
      `slug: ${slug}`,
      `title: "${escYaml(title)}"`,
      `d: "${escYaml(d)}"`,
      `date: "${date}"`,
      `r: "${readTime}"`,
      `category: ${category}`,
    ];
    if (coverPath) fmLines.push(`cover: "${coverPath}"`);
    if (coverAlt) fmLines.push(`coverAlt: "${escYaml(coverAlt)}"`);
    if (translator) fmLines.push(`translator: ${translator}`);
    fmLines.push("---", "");
    const frontmatter = fmLines.join("\n");

    const dir = path.join("content", "blog", slug);
    mkdirSync(dir, { recursive: true });
    const enPath = path.join(dir, "en.md");
    writeFileSync(enPath, frontmatter + body + "\n");
    processed.push({ id: page.id, slug });
    console.log(`[notion] wrote ${enPath} (${readTime})`);
  }

  // Emit the processed list for the GHA workflow to consume.
  const json = JSON.stringify(processed);
  console.log(`[notion] processed=${json}`);
  if (process.env.GITHUB_OUTPUT) {
    appendFileSync(process.env.GITHUB_OUTPUT, `processed=${json}\n`);
    appendFileSync(process.env.GITHUB_OUTPUT, `count=${processed.length}\n`);
  }
}

main().catch((err) => {
  console.error(`[notion] fatal: ${err.message}`);
  process.exit(1);
});
